### ISSUE TITLE
[ BUG ] Proper docs and/or template setup

### ISSUE THREAD

**Issue by docimin** [mrzachnugent/react-native-reusables#108]
Not really a bug, but you have very limited ways to contact

Honestly, it's looking great and all, but I have been annoyed as hell just to set it up using the damn template.

I just followed this simply: https://rnr-docs.vercel.app/getting-started/initial-setup/, but every time I run into the issue that your packages are not in the registry.

`'@rnr/accordion@*' is not in this registry.`, for example.

Can you describe your docs better, or fix your template?
There's also no proper consistency between your templates and setting it up manually.

Because they are so much different, there's no knowing which path to actually take.

**Comment by mrzachnugent** [comment]
@docimin could you help me by providing step by step what you did from start to finish?

From the instructions in that link, you should not have @rnr/accordion@ anywhere in your codebase.

By providing the steps you took from the start, I can adjust the miscommunication in the docs.

**Comment by docimin** [comment]
@mrzachnugent Hey.

https://github.com/mrzachnugent/react-native-reusables/blob/main/apps/showcase/package.json

This contains your packages.

Just follow the link I sent before, go into the showcase folder and type npm i (pnpm is same).

You'll get errors that your packages do not exist.

I can make a step-by-step in a bit, but basically just follow the template install.

The same goes for manual install, as there's no consistency and the UI files are referring to the wrong props in primitives, but i'll come back to that in probably a new issue.

**Comment by mrzachnugent** [comment]
@docimin The docs for https://rnr-docs.vercel.app/getting-started/initial-setup/ are not for the `/apps/showcase` app.

This repo uses a monorepo which is why there are packages in the `/apps/showcase` that are not in the npm registry. It is not made to be used as a template. If you want to run the showcase app on your machine, please follow the instruction for [How to use/For this repository](https://github.com/mrzachnugent/react-native-reusables?tab=readme-ov-file#how-to-use) in this repo's README .

From the https://rnr-docs.vercel.app/getting-started/initial-setup/ can you please point out how you got to the showcase app's code?

**Comment by docimin** [comment]
> From the https://rnr-docs.vercel.app/getting-started/initial-setup/ can you please point out how you got to the showcase app's code?

Since it goes towards the starter-base, I figured you can choose any of the 3 apps.
Thanks for the help, I'll try out the normal starter-base and see.

**Comment by mrzachnugent** [comment]
@docimin No problem! 

Feel free to open another issue if you run into problems with the documentation. If you can provide exact text references, it would be greatly appreciated.
