### ISSUE TITLE
[ BUG ] error with className

### ISSUE THREAD

**Issue by m4rc1nn** [mrzachnugent/react-native-reusables#114]
![Zrzut ekranu 2024-03-23 o 12 20 55](https://github.com/mrzachnugent/react-native-reusables/assets/31964364/399f4126-a34f-4047-a2c2-75138ec4bb28)

**Comment by mrzachnugent** [comment]
@m4rc1nn This looks like it might be a NativeWind installation issue.

Try this: https://www.nativewind.dev/v4/getting-started/typescript

**Comment by singh-jay** [comment]
In my case with Expo, it's working fine, but when I add a next.js app in the apps directory then only get this error. Is it possible to use these components in next.js with react-native-web? I tried the installation steps from - https://www.nativewind.dev/v4/getting-started/typescript, still getting the same error.

**Comment by mrzachnugent** [comment]
@m4rc1nn I guess it depends how you are using it. 

I am going to close this issue since it is not related to `react-native-reusables`.

Here are some resources that might be helpful:
- [Solito](https://solito.dev/): Next js + React Native Framework
- [Expo docs](https://docs.expo.dev/guides/using-nextjs/): Use Next.js with Expo for Web

**Comment by singh-jay** [comment]
The problem was with the react-native version 0.73.6 when downgraded to 0.76.4, working fine with the next.js typescript also added src-env.d.ts in root next,js dir.
