### ISSUE TITLE
[ BUG ] Warning: You are setting the style `{ userSelect: ... }` as a prop. You should nest it in a style object. E.g. `{ style: { userSelect: ... } }`

### ISSUE THREAD

**Issue by weilueluo** [mrzachnugent/react-native-reusables#126]
**Describe the bug**
When trying out the `Tabs` demo on my phone, the UI looks off when I tab on `Password` tab

**To Reproduce**
1. Create a new project: expo + rnr
2. Create a new screen following usage from https://rnr-docs.vercel.app/components/tabs/
3. Download expo-go and open up the app from IOS phone
4. Click on the `Password` tab

**Expected behavior**
Upon clicking on `Password` tab, the background of the `Account` tab should turn to background color

**Screenshots**
**Incorrect display(demo in IOS)**
![Image_20240404215705](https://github.com/mrzachnugent/react-native-reusables/assets/39546701/a6fa69b4-e5c6-4129-923c-81ed37469cee)
**Expected display(demo in web)**
![Screenshot 2024-04-04 215809](https://github.com/mrzachnugent/react-native-reusables/assets/39546701/58670b47-85a9-457a-a9c7-64502e3d6619)

**Platform (please complete the following information):**
 - Type: Expo Go (I think is Device?)[eg: Browser, Simulator, Emulator, Device]
 - OS: IOS
 - Browser: chrome

**Additional context**
The button still works as expected, but the UI looks off.

```
 ERROR  Warning: You are setting the style `{ userSelect: ... }` as a prop. You should nest it in a style object. E.g. `{ style: { userSelect: ... } }`
 ERROR  Warning: You are setting the style `{ userSelect: ... }` as a prop. You should nest it in a style object. E.g. `{ style: { userSelect: ... } }`
```

**Comment by weilueluo** [comment]
gone after `npm update`

**Comment by ahmadbakhshi** [comment]
I am getting exact same error when I run on Web and IOS simultaneously .

"nativewind": "^4.0.36",
"expo": "~51.0.9",
"react-native-web": "~0.19.12",

I've tried with expo go and dev build both and I am getting this exact error everytime along with many other warnings
similar to this 
`The previous warning was caused by a component with these props: ["className","role","onPress","children"]. Some props could not be stringified, so only the keys are shown. 
    at CssInterop.Pressable` related to `CssInterop.Pressable`
