### ISSUE TITLE
[ FEATURE ] Docs: showcase

### ISSUE THREAD

**Issue by guibzo** [mrzachnugent/react-native-reusables#239]
**Is your feature request related to a problem? Please describe.**
It is rather inconvenient to not have this already.

**Describe the solution you'd like**
I would love to see components showcase in the docs. We know that some of them would be limited due to web RN being limited,  but even screenshots or half functioning components would already help to visualize both the design and functionality,  then check if they will fit properly into our projects.

Also other thing that shadcn does well and could be provided on Reusables is providing code templates of common use-cases, for example Checkbox being integrated with RHF and Form.

![image](https://github.com/user-attachments/assets/be03bab8-ca7b-4e33-b5fa-20e3a3c83a3b)

![image](https://github.com/user-attachments/assets/d1e4c602-7e0c-4dcf-89ba-4f80e6209537)

**Comment by mrzachnugent** [comment]
Closing due to duplicated issue: https://github.com/mrzachnugent/react-native-reusables/issues/132

You can see all of the web component demos here: https://rnr-showcase.vercel.app/ and on a component's page in [the docs](https://rnr-docs.vercel.app/getting-started/introduction/) there is a demo button which brings you to the specific component from in the showcase website
<img width="1248" alt="Screenshot 2024-10-13 at 2 46 44 PM" src="https://github.com/user-attachments/assets/1f994875-0a61-4082-a737-dbb7273caced">
