### ISSUE TITLE
[FEATURE] Add Component Previews or Screenshots to Documentation for Better Usability

### ISSUE THREAD

**Issue by WalidMoua** [mrzachnugent/react-native-reusables#256]
**Is your feature request related to a problem? Please describe.**
Currently, there isn't a way to directly view each component from the docs page, which is inconvenient.

**Describe the solution you'd like**
I would like to see Expo's component preview integrated into the docs, allowing users to visualize each reusable component easily.

**Describe alternatives you've considered**
Alternatively, adding static screenshots for each component could provide a low-effort, high-impact solution.

**Additional context**
Including visual representations will likely enhance adoption among new users.

**Comment by mrzachnugent** [comment]
Closing due to duplicated issue: https://github.com/mrzachnugent/react-native-reusables/issues/132

You can see all of the web component demos here: https://rnr-showcase.vercel.app/ and on a component's page in [the docs](https://rnr-docs.vercel.app/getting-started/introduction/) there is a demo button which brings you to the specific component from in the showcase website
<img width="1248" alt="Screenshot 2024-10-13 at 2 46 44 PM" src="https://github.com/user-attachments/assets/1f994875-0a61-4082-a737-dbb7273caced">
