### ISSUE TITLE
Questions: react-native-reusables vs ui.shadcn & `ui` vs `universal-ui`

### ISSUE THREAD

**Issue by subhanyousaf** [mrzachnugent/react-native-reusables#27]
Hey! I am new to RN, previously I have been developing react webapps. I have used shadcn countless times and I just love it. 

My question is, is there a doc/guide on how to set up RNR? I am a bit confused. Also what's the difference between reusables and universal?

**Comment by mrzachnugent** [comment]
Hey @subhanyousaf,

There are no docs at the moment but there will be. This repo is confusing because there are 2 projects in 1 and 3 different versions of components.

**The projects**
1. A React-Native version of ui.shadcn
2. A React-Native version of radix-ui/primitives (soon to be an npm package)

**Component versions**
1. `ui`: Mobile focused easily copy/pastes
2. `primitive`: Uses a soon to be npm package with little to no styling
3. `universal`: ui.shadcn components on the web and a mobile version of those components for native. It also uses a soon to be npm package.

The React-Native version of radix-ui/primitives will become an npm package and be removed from this repo. Once that is done, the plan is to replace the `ui` components with the `universal` components, then start writing the documentation.

For now, I would suggest using components found in `~/components/ui` since they do not use the "primitives". These components are mobile focused meaning some components do not look good or even work on react-native-web.

This is a good question so I will leave this issue open until it is properly documented.

**Comment by subhanyousaf** [comment]
Alright thanks! great work!

**Comment by Jrb1x** [comment]
> Hey @subhanyousaf,
> 
> There are no docs at the moment but there will be. This repo is confusing because there are 2 projects in 1 and 3 different versions of components.
> 
> **The projects**
> 
> 1. A React-Native version of ui.shadcn
> 2. A React-Native version of radix-ui/primitives (soon to be an npm package)
> 
> **Component versions**
> 
> 1. `ui`: Mobile focused easily copy/pastes
> 2. `primitive`: Uses a soon to be npm package with little to no styling
> 3. `universal`: ui.shadcn components on the web and a mobile version of those components for native. It also uses a soon to be npm package.
> 
> The React-Native version of radix-ui/primitives will become an npm package and be removed from this repo. Once that is done, the plan is to replace the `ui` components with the `universal` components, then start writing the documentation.
> 
> For now, I would suggest using components found in `~/components/ui` since they do not use the "primitives". These components are mobile focused meaning some components do not look good or even work on react-native-web.
> 
> This is a good question so I will leave this issue open until it is properly documented.

You're doing an amazing job and filling a huge gap in the web/mobile world. This is going to become very popular. I would put out a request for help from others to help out!

**Comment by mrzachnugent** [comment]
## Update
Primitives will no longer be its own npm package. Just like ui/shadcn, there will be a `ui` folder but now there will be a `primitives` folder.

### Folder Structure
```
├── components
│   ├── ui
│   ├── primitives
│ 
└── 
```

Proper documentation is in the works. There will be an initial setup guide, instructions per component.

**Comment by mrzachnugent** [comment]
Started creating the docs:
https://react-native-reusables.vercel.app/getting-started/introduction/

**Comment by emrahyurttutan** [comment]
@mrzachnugent 

First of all, congratulations. The project idea is very good.

I'm just curious about 2 things, is there a special reason why you don't manage this component part with monorepo logic instead of keeping it on the component side? 

Also, having the sample application directly in the project makes the package json very complex. 

But if you can open the documentation part with us, we can contribute and help you complete it quickly.

**Comment by mrzachnugent** [comment]
## Update 2:

The primitives as an npm package VS copy/pasted code is still up for discussions. You can vote here: https://github.com/mrzachnugent/react-native-reusables/discussions/49

**Comment by mrzachnugent** [comment]
@emrahyurttutan 

Thank you!

Moving it to a monorepo is under consideration at the moment. Once the docs are in place, it should help with the dependencies per component. 

For the documentation, it's still at a very early stage. 

I'm working on putting all of the pieces together for a good DX. Thank you for your patience.

**Comment by mrzachnugent** [comment]
Closing this issue since this information can be found at https://rnr-docs.vercel.app/getting-started/introduction/

Documentation adding each component is coming soon.
