### ISSUE TITLE
Open DropdownMenu after long press

### ISSUE THREAD

**Issue by ar3s3ru** [mrzachnugent/react-native-reusables#291]
The ["Programmatically Showing and Hiding Components"](https://rnr-docs.vercel.app/getting-started/common-patterns/#programmatically-showing-and-hiding-components) section describes how to open a component like `DropdownMenu` using `triggerRef.current.open()`.

However, it doesn't show how we can alter the position of the component to match where the `onPress`/`onLongPress` event happened.

@mrzachnugent can you clarify how is that supposed to work?

**Comment by mrzachnugent** [comment]
Hey @ar3s3ru, for the menu to open when you long press, you can use a [Context Menu](https://rnr-docs.vercel.app/components/context-menu/) instead of a dropdown menu. 

If you want to have the menu open based on press location, you will have to add some custom logic. You can pass `disablePositioningStyle` to the `DropdownMenu.Content` and implement your own styling logic that can be inspired from the [@rn-primtives/context-menu](https://github.com/roninoss/rn-primitives/blob/main/packages/context-menu/src/context-menu.tsx#L242) long press positioning.
