### ISSUE TITLE
[ BUG ] LucideIcon * imports  unnecessarily increase the  bundle size

### ISSUE THREAD

**Issue by atanaskanchev** [mrzachnugent/react-native-reusables#91]
**Describe the bug**
In couple of components LucideIcon is imported as `import * as LucideIcon from 'lucide-react-native'` but this increase the bundle size a lot.

**Expected behavior**
Have a generic icon component that accepts the LucideIcon props

**Screenshots**
![image](https://github.com/mrzachnugent/react-native-reusables/assets/4958587/24ddab5f-fea2-443e-9eea-388c00680cb4)

![image](https://github.com/mrzachnugent/react-native-reusables/assets/4958587/009d06cb-76c6-4aa2-88a2-7bc0ad45f84c)

**Comment by mrzachnugent** [comment]
@atanaskanchev Unfortunately, using the `import * as LucideIcon from 'lucide-react-native'` is the only way I know to get the expected behaviour mentioned. 

As per their docs (syntax has changed but outcome it the same): https://lucide.dev/guide/packages/lucide-react-native#icon-component-example, any generic icon component that accepts the LucideIcon props will increase bundle size.

Do you have a suggestion on how to achieve this?

Otherwise, the only other option would be to remove the generic icon component and require an explicit icon component instead.

**Comment by atanaskanchev** [comment]
> @atanaskanchev Unfortunately, using the `import * as LucideIcon from 'lucide-react-native'` is the only way I know to get the expected behaviour mentioned.
> 
> As per their docs (syntax has changed but outcome it the same): https://lucide.dev/guide/packages/lucide-react-native#icon-component-example, any generic icon component that accepts the LucideIcon props will increase bundle size.
> 
> Do you have a suggestion on how to achieve this?
> 
> Otherwise, the only other option would be to remove the generic icon component and require an explicit icon component instead.

I am not sure how we can solve this with LucideIcon as they do not offer a wrapper component. There are only handful of components (alert, label, toggle-group and toggle) that import lucide this way so I think passing explicit icon component would be ok
